version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/portfolio
permissions:
   - object: /
     pattern: "**"
     owner: ec2-user
     group: ec2-user

hooks:
   BeforeInstall:
    - location: scripts/install_node_modules.sh
      runas: root

   AfterInstall:
    - location: scripts/test.sh
      timeout: 5
      runas: ec2-user

   ApplicationStart:
    - location: scripts/run.sh
      timeout: 5
      runas: root

   ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
